@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    ListTVAComponent,
    TvaDetailComponent,
    TvaFormComponent,
    ProduitComponent,
    CompteListComponent,
    CompteFormComponent,
    EcritureListComponent,
    EcritureFormComponent,
    GestionComptableComponent,
    JournalComponent,
    GrandLivreComponent,
    BalanceComponent,
    BilanComponent,
    ResultatComponent,
    DashboardComponent, // Attention : était en double
    FournisseursComponent,
    CommandesComponent,
    ListDFComponent,
    DFFormComponent,
    DFDetailComponent,
    MSComponent,
    UtilisateurComponent,
    AddUtilisateurComponent,
    UtilisateurDetailsComponent,

    // Client / Facturation (gestion_facturation_client)
    ClientListComponent,
    ClientFormComponent,
    DevisFormComponent,
    DevisListComponent,
    FactureListComponent,
    RelanceAutomationComponent,
    ReportingComponent,

    // Rôles & Fiscalité (main)
    RoleComponent,
    AddRoleComponent,
    RoleDetailsComponent,
    GenerateDeclarationDialogComponent,
    GenerateTvaDialogComponent,
    DFTVAComponent,
    TvaManagementComponent,
    DfManagementComponent,
    FiscalDashboardComponent,
    SimulationFiscaleComponent,
    FiscalStatisticsComponent,
    ShortenIdPipe,
    StockDashboardComponent
  ],
